<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <PackageVersion>0.17.0</PackageVersion>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageOutputPath>bin/packages</PackageOutputPath>
    </PropertyGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\..\Base\Mcma.Api\Mcma.Api.csproj" />
    </ItemGroup>

</Project>
