<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>Latest</LangVersion>
        <PackageVersion>0.16.1</PackageVersion>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageOutputPath>bin/packages</PackageOutputPath>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\..\Base\Mcma.WorkerInvoker\Mcma.WorkerInvoker.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="Google.Cloud.PubSub.V1" Version="3.32.0" />
    </ItemGroup>

</Project>
