<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>Latest</LangVersion>
        <PackageVersion>0.17.2</PackageVersion>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageOutputPath>bin/packages</PackageOutputPath>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="../../Base/Mcma.Client/Mcma.Client.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="Google.Apis.Oauth2.v2" Version="1.68.0.1869" />
    </ItemGroup>

</Project>
