<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <PackageVersion>0.16.1</PackageVersion>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageOutputPath>bin/packages</PackageOutputPath>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Base\Mcma.Data\Mcma.Data.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MongoDB.Driver" Version="3.6.0" />
      <PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.3" />
    </ItemGroup>

</Project>
